w

diff --git a/cloudy b/cloudy
--- a/cloudy
+++ b/cloudy
@@ -179,6 +179,10 @@ cmd_cmd(){
 
 cmd_get(){
     assert_lockfile_present
+    if [ -z "$1" ]; then
+        echo "Missing file path."
+        exit 1
+    fi
     m_scp $ID $IP $1
 }
 
